"""
Step 7: Critique Agent Node
Validates the generated architecture diagram for accuracy and completeness.
Uses the strong reasoning GPT-OSS model via OpenRouter.

Input:  AnalysisState with reactflow_nodes, reactflow_edges, parsed_files
Output: AnalysisState with critique_passed, critique_feedback, retry_count
"""

from typing import Dict, Any, List
from app.agents.state import AnalysisState
from app.core.llm import get_critique_llm
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser

SYSTEM_PROMPT = """
You are a Quality Assurance Architect. Your job is to critique an architecture diagram generated by another AI.

You will receive:
1. A summary of the actual files in the codebase.
2. The generated React Flow diagram (nodes and edges).

### Your Task:
Check if the diagram is accurate and representative of the codebase.
1. Are there any major components/files missing from the diagram?
2. Are there any nodes in the diagram that DO NOT exist in the actual code (hallucinations)?
3. Do the connections (edges) make logical sense based on the file structure?

### Output Format:
You MUST return ONLY a JSON object with this exact structure:
{{
  "critique_passed": true/false,
  "critique_feedback": "Detailed explanation of why it passed or failed. If failed, list specific missing or hallucinated nodes."
}}

If the diagram is generally good and covers the main entry points and core logic, mark 'critique_passed' as true. Only fail if there are clear errors or significant omissions.
"""

USER_PROMPT_TEMPLATE = """
ACTUAL CODEBASE STRUCTURE:
{structure_summary}

GENERATED DIAGRAM NODES:
{nodes}

GENERATED DIAGRAM EDGES:
{edges}
"""

def critique_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    LangGraph node: Critiques the architecture diagram.
    """
    nodes = state.get("reactflow_nodes", [])
    edges = state.get("reactflow_edges", [])
    parsed_files = state.get("parsed_files", [])
    retry_count = state.get("retry_count", 0)

    # 1. Prepare structure summary for the critique
    summary_lines = []
    for pf in parsed_files:
        summary_lines.append(f"- {pf['path']} ({pf['language']})")
    structure_summary = "\n".join(summary_lines[:100])

    try:
        # 2. Setup LLM and Prompt
        llm = get_critique_llm()
        prompt = ChatPromptTemplate.from_messages([
            ("system", SYSTEM_PROMPT),
            ("user", USER_PROMPT_TEMPLATE)
        ])
        
        chain = prompt | llm | JsonOutputParser()

        # 3. Invoke LLM
        response = chain.invoke({
            "structure_summary": structure_summary,
            "nodes": json.dumps(nodes),
            "edges": json.dumps(edges)
        })

        passed = response.get("critique_passed", False)
        feedback = response.get("critique_feedback", "No feedback provided.")

        return {
            "critique_passed": passed,
            "critique_feedback": feedback,
            "retry_count": retry_count + 1,
            "current_step": "critique_complete",
            "progress_log": [
                f"{'✅' if passed else '⚠️'} Critique {'passed' if passed else 'failed'}: {feedback}"
            ]
        }

    except Exception as e:
        # If critique fails technically, we'll just let it pass to avoid infinite blocks,
        # but log the warning.
        return {
            "critique_passed": True, 
            "critique_feedback": f"Critique failed technically: {str(e)}",
            "retry_count": retry_count + 1,
            "current_step": "critique_complete",
            "progress_log": [f"⚠️ Critique agent technical error (proceeding anyway): {str(e)}"]
        }

import json # Needed for json.dumps
