"""add_reactflow_json

Revision ID: 494af8b350a0
Revises: fc1da5391fe1
Create Date: 2026-05-24 13:37:15.495631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '494af8b350a0'
down_revision: Union[str, None] = 'fc1da5391fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagrams', sa.Column('reactflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'reactflow_json')
    # ### end Alembic commands ###
