"""add logs column to repos

Revision ID: 57671c90d880
Revises: 494af8b350a0
Create Date: 2026-05-24 23:53:55.977764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57671c90d880'
down_revision: Union[str, None] = '494af8b350a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('logs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'logs')
    # ### end Alembic commands ###
