"""Add title and updated_at to chat sessions

Revision ID: 6bb9f0333e1a
Revises: a1e4ebe7f25b
Create Date: 2026-06-23 16:46:39.950369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb9f0333e1a'
down_revision: Union[str, None] = 'a1e4ebe7f25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'updated_at')
    op.drop_column('chat_sessions', 'title')
    # ### end Alembic commands ###
