"""add_user_id_to_existing_tables

Revision ID: a1e4ebe7f25b
Revises: 6ccd4c457410
Create Date: 2026-06-19 16:59:44.128215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e4ebe7f25b'
down_revision: Union[str, None] = '6ccd4c457410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('diagrams', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'diagrams', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('qa_queries', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'qa_queries', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('repos', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'repos', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repos', type_='foreignkey')
    op.drop_column('repos', 'user_id')
    op.drop_constraint(None, 'qa_queries', type_='foreignkey')
    op.drop_column('qa_queries', 'user_id')
    op.drop_constraint(None, 'diagrams', type_='foreignkey')
    op.drop_column('diagrams', 'user_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
