"""initial schema

Revision ID: fc1da5391fe1
Revises: 
Create Date: 2026-04-17 15:28:30.885735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc1da5391fe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagrams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('diagram_type', sa.String(), nullable=True),
    sa.Column('mermaid_syntax', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('confidence_file_count', sa.Integer(), nullable=True),
    sa.Column('contributing_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=True),
    sa.Column('stale_reason', sa.String(), nullable=True),
    sa.Column('stale_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_commit_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('highlight_node_id', sa.String(), nullable=True),
    sa.Column('code_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('diagrams')
    op.drop_table('chat_sessions')
    op.drop_table('repos')
    # ### end Alembic commands ###
